### ISSUE TITLE
Help Understanding and Setup of ADW Wallets

### ISSUE THREAD

**Issue by chipbaber** [chipbaber/CodeInnovate-HamtonInc-Coder_Rock#1]
We need a better understanding of the difference between regional wallets and instance wallets. 

![image](https://user-images.githubusercontent.com/32364785/78067846-6749c380-7365-11ea-8dd9-0d34de652092.png)

We need a walk through of how and which to use in TOAD for our use case. Need help setting up connection in TOAD.

**Comment by chipbaber** [comment]
Derrick, Can you take a look and provide the documentation links for this groups.

**Comment by dgcameron** [comment]
[Take a look at this doc on regional versus instance wallets.](https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/connect-download-wallet.html#GUID-B06202D2-0597-41AA-9481-3B174F75D4B1)

**Comment by dgcameron** [comment]
Also, any third party tool, including Toad can connect using instant client.  See [this](https://forums.toadworld.com/t/toad-connection-to-oracle-cloud-autonomous-database-using-wallet/48202) for more info.
